name: shelter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  cloud_firestore: ^3.1.4
  dotted_border: ^2.0.0+2
  firebase_storage: ^10.2.4
  toggle_switch: ^1.3.0
  timeago: ^3.1.0
  enum_to_string: ^2.0.1
  form_builder_image_picker: ^2.0.0
  form_builder_extra_fields: ^7.0.0
  firebase_auth: ^3.3.3
  adaptive_dialog: ^1.2.0
  lottie: ^1.2.1
  firebase_core: ^1.10.5
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  fancy_bottom_navigation: ^0.3.3
  logger: ^1.1.0
  flutter_easyloading: ^3.0.3
  flutter_hooks: ^0.18.1
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.10
  line_icons: ^2.0.1
  sprintf: ^6.0.0
  hooks_riverpod: ^1.0.3
  auto_route: ^3.1.3
  dio_logger: ^4.0.8+8
  easy_localization: ^3.0.0
  easy_localization_loader: ^1.0.0
  responsive_builder: ^0.4.1
  dio_cache_interceptor: ^3.0.1
  connectivity: ^3.0.6
  flutter_form_builder: ^7.0.0
  # dio_cache_interceptor_hive_store: ^3.0.1
  path_provider: ^2.0.3
  local_auth: ^1.1.7
  onesignal_flutter: ^3.2.7
  google_fonts: ^2.1.0
  encrypt: ^5.0.1
  websafe_svg: ^2.0.0+2
  form_builder_validators: ^7.2.0
  form_builder_phone_field: ^1.0.0-beta.0
  # form_builder_map_field: ^1.0.0-alpha.1
  cached_network_image: ^3.2.0
  google_maps_flutter: ^2.1.1
  device_info: ^2.0.3
  app_settings: ^4.1.1
  introduction_screen: ^2.1.0
  full_screen_image: ^1.0.2
  photo_view: ^0.13.0
  # lints: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  auto_route_generator: ^3.1.0
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/luncher/logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/lang/
    - assets/images/
    - assets/animation/
